# Site settings
baseurl: ''
url: 'http://ember-cli.com'

# Build settings
markdown: kramdown
exclude: ['node_modules', 'vendor']

# TODO: Automate version bump on release
version: 2.4.2

gems:
  - jekyll-feed
  - github-pages
