# Site settings
baseurl: ''
url: 'http://ember-cli.com'

# Build settings
markdown: kramdown
exclude: ['node_modules', 'vendor']

# TODO: Automate version bump on release
version: 1.13.15

gems:
  - jekyll-feed
  - github-pages
